import { NFT, User, Collection, Transaction } from '../types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user1',
    username: 'cosmicCreator',
    avatarUrl: 'https://images.pexels.com/photos/7148384/pexels-photo-7148384.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    isVerified: true,
    totalSales: 142,
    totalNFTs: 38,
    joinedDate: '2023-05-15',
  },
  {
    id: 'user2',
    username: 'digitalArtisan',
    avatarUrl: 'https://images.pexels.com/photos/8090137/pexels-photo-8090137.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    isVerified: true,
    totalSales: 89,
    totalNFTs: 24,
    joinedDate: '2023-07-22',
  },
  {
    id: 'user3',
    username: 'cryptoVisionary',
    avatarUrl: 'https://images.pexels.com/photos/6577903/pexels-photo-6577903.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    isVerified: false,
    totalSales: 35,
    totalNFTs: 12,
    joinedDate: '2023-09-10',
  },
  {
    id: 'user4',
    username: 'blockchainDreamer',
    avatarUrl: 'https://images.pexels.com/photos/11131436/pexels-photo-11131436.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    isVerified: false,
    totalSales: 17,
    totalNFTs: 8,
    joinedDate: '2024-01-05',
  },
];

// Mock NFTs
export const mockFeaturedNFTs: NFT[] = [
  {
    id: 'nft1',
    name: 'Ethereal Dreamscape #42',
    description: 'A mesmerizing journey through digital realms, where reality bends and imagination takes flight.',
    imageUrl: 'https://images.pexels.com/photos/7788009/pexels-photo-7788009.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[0],
    owner: mockUsers[2],
    price: 45.5,
    currency: 'ICP',
    isForSale: true,
    collectionName: 'Ethereal Dreamscapes',
    createdAt: '2024-03-15',
    attributes: [
      { trait_type: 'Background', value: 'Cosmic' },
      { trait_type: 'Style', value: 'Abstract' },
      { trait_type: 'Colors', value: 'Vibrant' },
    ],
    likes: 423,
    views: 1892,
  },
  {
    id: 'nft2',
    name: 'Digital Genesis #12',
    description: 'The birth of a new digital era, captured in a moment of creation.',
    imageUrl: 'https://images.pexels.com/photos/5017779/pexels-photo-5017779.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[1],
    owner: mockUsers[1],
    price: 32.8,
    currency: 'ICP',
    isForSale: true,
    collectionName: 'Digital Genesis',
    createdAt: '2024-02-28',
    attributes: [
      { trait_type: 'Background', value: 'Digital Void' },
      { trait_type: 'Style', value: 'Futuristic' },
      { trait_type: 'Rarity', value: 'Rare' },
    ],
    likes: 287,
    views: 1145,
  },
  {
    id: 'nft3',
    name: 'Quantum Landscape #7',
    description: 'A visualization of quantum mechanics principles in an immersive landscape.',
    imageUrl: 'https://images.pexels.com/photos/8107191/pexels-photo-8107191.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[2],
    owner: mockUsers[0],
    price: 28.5,
    currency: 'ICP',
    isForSale: false,
    collectionName: 'Quantum Visions',
    createdAt: '2024-01-10',
    attributes: [
      { trait_type: 'Dimension', value: 'Multi-layered' },
      { trait_type: 'Style', value: 'Scientific' },
      { trait_type: 'Complexity', value: 'High' },
    ],
    likes: 198,
    views: 876,
  },
  {
    id: 'nft4',
    name: 'Cyber Nomad #23',
    description: 'A digital wanderer traversing the vast expanses of the metaverse.',
    imageUrl: 'https://images.pexels.com/photos/10127069/pexels-photo-10127069.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[3],
    owner: mockUsers[3],
    price: 15.75,
    currency: 'ICP',
    isForSale: true,
    collectionName: 'Cyber Nomads',
    createdAt: '2024-04-05',
    attributes: [
      { trait_type: 'Environment', value: 'Cyberpunk' },
      { trait_type: 'Style', value: 'Digital Art' },
      { trait_type: 'Mood', value: 'Mysterious' },
    ],
    likes: 156,
    views: 723,
  },
  {
    id: 'nft5',
    name: 'Neon Dreams #18',
    description: 'A vibrant neon-lit dreamscape that pulses with digital energy.',
    imageUrl: 'https://images.pexels.com/photos/15178293/pexels-photo-15178293/free-photo-of-futuristic-woman-with-purple-and-blue-lights.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[0],
    owner: mockUsers[3],
    price: 22.4,
    currency: 'ICP',
    isForSale: true,
    collectionName: 'Neon Dreams',
    createdAt: '2024-03-22',
    attributes: [
      { trait_type: 'Lighting', value: 'Neon' },
      { trait_type: 'Style', value: 'Retro-futuristic' },
      { trait_type: 'Setting', value: 'Urban' },
    ],
    likes: 231,
    views: 1024,
  },
  {
    id: 'nft6',
    name: 'Astral Projection #9',
    description: 'A journey beyond the physical realm into the astral plane.',
    imageUrl: 'https://images.pexels.com/photos/8107191/pexels-photo-8107191.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[1],
    owner: mockUsers[1],
    price: 38.2,
    currency: 'ICP',
    isForSale: true,
    collectionName: 'Astral Journeys',
    createdAt: '2024-02-15',
    attributes: [
      { trait_type: 'Dimension', value: 'Astral' },
      { trait_type: 'Style', value: 'Spiritual' },
      { trait_type: 'Energy', value: 'High Vibration' },
    ],
    likes: 342,
    views: 1567,
  },
  {
    id: 'nft7',
    name: 'Techno Shaman #3',
    description: 'A fusion of ancient shamanic wisdom with futuristic technology.',
    imageUrl: 'https://images.pexels.com/photos/15178295/pexels-photo-15178295/free-photo-of-futuristic-woman-with-ai-technology.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[2],
    owner: mockUsers[2],
    price: 29.9,
    currency: 'ICP',
    isForSale: false,
    collectionName: 'Techno Shamans',
    createdAt: '2024-01-28',
    attributes: [
      { trait_type: 'Fusion', value: 'Ancient-Future' },
      { trait_type: 'Style', value: 'Tribal Tech' },
      { trait_type: 'Power', value: 'Transformative' },
    ],
    likes: 187,
    views: 823,
  },
  {
    id: 'nft8',
    name: 'Holographic Entity #15',
    description: 'A sentient holographic being from a dimension of pure information.',
    imageUrl: 'https://images.pexels.com/photos/5011647/pexels-photo-5011647.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[3],
    owner: mockUsers[0],
    price: 17.8,
    currency: 'ICP',
    isForSale: true,
    collectionName: 'Holographic Entities',
    createdAt: '2024-04-02',
    attributes: [
      { trait_type: 'Composition', value: 'Holographic' },
      { trait_type: 'Intelligence', value: 'Sentient' },
      { trait_type: 'Origin', value: 'Information Dimension' },
    ],
    likes: 143,
    views: 678,
  },
];

// Mock Collections
export const mockTopCollections: Collection[] = [
  {
    id: 'collection1',
    name: 'Ethereal Dreamscapes',
    description: 'A collection of mesmerizing digital realms where reality bends and imagination takes flight.',
    coverImageUrl: 'https://images.pexels.com/photos/7788009/pexels-photo-7788009.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[0],
    itemCount: 42,
    floorPrice: 28.5,
    totalVolume: 1245.8,
    currency: 'ICP',
  },
  {
    id: 'collection2',
    name: 'Digital Genesis',
    description: 'Witness the birth of a new digital era through this groundbreaking collection.',
    coverImageUrl: 'https://images.pexels.com/photos/5017779/pexels-photo-5017779.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[1],
    itemCount: 25,
    floorPrice: 32.8,
    totalVolume: 875.4,
    currency: 'ICP',
  },
  {
    id: 'collection3',
    name: 'Quantum Visions',
    description: 'Visualizations of quantum mechanics principles in immersive digital landscapes.',
    coverImageUrl: 'https://images.pexels.com/photos/8107191/pexels-photo-8107191.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[2],
    itemCount: 18,
    floorPrice: 15.2,
    totalVolume: 325.6,
    currency: 'ICP',
  },
  {
    id: 'collection4',
    name: 'Cyber Nomads',
    description: 'Join the digital wanderers traversing the vast expanses of the metaverse.',
    coverImageUrl: 'https://images.pexels.com/photos/10127069/pexels-photo-10127069.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[3],
    itemCount: 30,
    floorPrice: 12.5,
    totalVolume: 412.3,
    currency: 'ICP',
  },
  {
    id: 'collection5',
    name: 'Neon Dreams',
    description: 'Vibrant neon-lit dreamscapes that pulse with digital energy.',
    coverImageUrl: 'https://images.pexels.com/photos/15178293/pexels-photo-15178293/free-photo-of-futuristic-woman-with-purple-and-blue-lights.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[0],
    itemCount: 22,
    floorPrice: 18.4,
    totalVolume: 520.7,
    currency: 'ICP',
  },
  {
    id: 'collection6',
    name: 'Holographic Entities',
    description: 'Sentient holographic beings from a dimension of pure information.',
    coverImageUrl: 'https://images.pexels.com/photos/5011647/pexels-photo-5011647.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    creator: mockUsers[3],
    itemCount: 15,
    floorPrice: 17.8,
    totalVolume: 285.2,
    currency: 'ICP',
  },
];

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: 'tx1',
    type: 'sale',
    nft: mockFeaturedNFTs[0],
    from: mockUsers[0],
    to: mockUsers[2],
    price: 45.5,
    currency: 'ICP',
    timestamp: '2024-04-10T14:32:15Z',
  },
  {
    id: 'tx2',
    type: 'mint',
    nft: mockFeaturedNFTs[1],
    from: mockUsers[1],
    to: mockUsers[1],
    price: 0,
    currency: 'ICP',
    timestamp: '2024-02-28T09:15:22Z',
  },
  {
    id: 'tx3',
    type: 'transfer',
    nft: mockFeaturedNFTs[2],
    from: mockUsers[2],
    to: mockUsers[0],
    price: 0,
    currency: 'ICP',
    timestamp: '2024-03-18T16:45:30Z',
  },
  {
    id: 'tx4',
    type: 'listing',
    nft: mockFeaturedNFTs[3],
    from: mockUsers[3],
    to: mockUsers[3],
    price: 15.75,
    currency: 'ICP',
    timestamp: '2024-04-05T11:22:45Z',
  },
  {
    id: 'tx5',
    type: 'offer',
    nft: mockFeaturedNFTs[4],
    from: mockUsers[3],
    to: mockUsers[0],
    price: 20.8,
    currency: 'ICP',
    timestamp: '2024-03-25T13:10:18Z',
  },
];